version: "3.8"

services:
  oracle:
    build: .
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - ./sql/init.sql:/container-entrypoint-initdb.d/init.sql
