-- Criação do usuário e permissões
CREATE USER dev IDENTIFIED BY devpass;
GRANT CONNECT, RESOURCE TO dev;
ALTER USER dev QUOTA UNLIMITED ON USERS;

-- Define o schema para a sessão atual
ALTER SESSION SET CURRENT_SCHEMA = dev;

--------------------------------------------------------------------------------
-- TABELAS
--------------------------------------------------------------------------------
-- CLIENTES
CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    idade NUMBER
);

-- PRODUTOS
CREATE TABLE produtos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    preco NUMBER(10,2) NOT NULL
);

-- PEDIDOS
CREATE TABLE pedidos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER(5) NOT NULL,
    data_pedido DATE DEFAULT SYSDATE,
    CONSTRAINT fk_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);

--------------------------------------------------------------------------------
-- PROCEDURES
--------------------------------------------------------------------------------
-- Inserir cliente
CREATE OR REPLACE PROCEDURE sp_inserir_cliente (
    p_nome IN clientes.nome%TYPE,
    p_idade IN clientes.idade%TYPE
) AS
BEGIN
    INSERT INTO clientes (nome, idade)
    VALUES (p_nome, p_idade);
END;
/

-- Inserir produto
CREATE OR REPLACE PROCEDURE sp_inserir_produto (
    p_nome IN produtos.nome%TYPE,
    p_preco IN produtos.preco%TYPE
) AS
BEGIN
    INSERT INTO produtos (nome, preco)
    VALUES (p_nome, p_preco);
END;
/

-- Criar pedido
CREATE OR REPLACE PROCEDURE sp_criar_pedido (
    p_cliente_id IN pedidos.cliente_id%TYPE,
    p_produto_id IN pedidos.produto_id%TYPE,
    p_quantidade IN pedidos.quantidade%TYPE
) AS
BEGIN
    INSERT INTO pedidos (cliente_id, produto_id, quantidade)
    VALUES (p_cliente_id, p_produto_id, p_quantidade);
END;
/

--------------------------------------------------------------------------------
-- FUNCTIONS
--------------------------------------------------------------------------------
-- Obter idade do cliente
CREATE OR REPLACE FUNCTION fn_obter_idade (
    p_id IN clientes.id%TYPE
)
RETURN NUMBER IS
    v_idade clientes.idade%TYPE;
BEGIN
    SELECT idade INTO v_idade
    FROM clientes
    WHERE id = p_id;
    RETURN v_idade;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

-- Calcular total de um pedido
CREATE OR REPLACE FUNCTION fn_total_pedido (
    p_pedido_id IN pedidos.id%TYPE
)
RETURN NUMBER IS
    v_total NUMBER(10,2);
BEGIN
    SELECT p.preco * pd.quantidade
    INTO v_total
    FROM pedidos pd
    JOIN produtos p ON p.id = pd.produto_id
    WHERE pd.id = p_pedido_id;
    RETURN v_total;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

--------------------------------------------------------------------------------
-- VIEWS
--------------------------------------------------------------------------------
-- Total de pedidos por cliente
CREATE OR REPLACE VIEW vw_total_pedidos_cliente AS
SELECT 
    c.id AS cliente_id,
    c.nome,
    COUNT(p.id) AS total_pedidos
FROM clientes c
LEFT JOIN pedidos p ON p.cliente_id = c.id
GROUP BY c.id, c.nome;

-- Total gasto por cliente
CREATE OR REPLACE VIEW vw_total_gasto_cliente AS
SELECT 
    c.id AS cliente_id,
    c.nome,
    SUM(fn_total_pedido(p.id)) AS total_gasto
FROM clientes c
LEFT JOIN pedidos p ON p.cliente_id = c.id
GROUP BY c.id, c.nome
ORDER BY total_gasto DESC;

--------------------------------------------------------------------------------
-- DADOS INICIAIS DE TESTE
--------------------------------------------------------------------------------
BEGIN
    sp_inserir_cliente('Thales', 28);
    sp_inserir_cliente('Julio', 25);

    sp_inserir_produto('Notebook', 3500);
    sp_inserir_produto('Mouse', 120);

    sp_criar_pedido(1, 1, 1);
    sp_criar_pedido(1, 2, 2);
    sp_criar_pedido(2, 2, 1);
END;
/
